spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/springapp
    username: leo
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
